<?xml version="1.0" encoding="utf-8"?><Database Name="Geography" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WINDOWS10\SQLEXPRESS;Initial Catalog=Geography;Integrated Security=True" SettingsObjectName="wpu221_lesson3__LINQ.Properties.Settings" SettingsPropertyName="GeographyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Countries">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Сapital" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartOfTheWorld" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Area" Type="System.Single" DbType="Real" CanBeNull="true" />
    </Type>
  </Table>
</Database>